name: Bot Deployment

on:
  push:
    branches: [ "master" ]

jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          docker stop deploy_app_1
          docker container prune -f
          docker rmi deploy_app:latest
          cd /root/github.com/meximonster/go-discordbot/deploy
          git pull
          docker-compose up -d