name: Bot Deployment

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: meximonster/discord-bot
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd ${{ secrets.APP_FOLDER }}
          docker-compose down
          docker-compose pull
          git pull
          docker-compose up -d
